### ISSUE TITLE
Thank you for such a good SCSS extension, but I found a bug about compressing CSS to min.css

### ISSUE THREAD

**Issue by wlq673736503** [Flowko/ScssToCssFlow#2]
The details are as follows: I modified the default 'SCSS to CSS compile: Output' and set it to either 'compressed' or 'expanded' separately, which does not take effect. It must be set to 'compressed | expanded' to compress files. However, this will result in '*. css' and' *. min. css', and I only want '*. min. css'
![image](https://user-images.githubusercontent.com/37679561/232393244-d3fe76ce-bd12-431d-8812-1baf08fc2a71.png)
![image](https://user-images.githubusercontent.com/37679561/232393294-ede32272-d940-4a37-a637-5d243dca2d4f.png)

**Comment by Flowko** [comment]
hi thanks for ur feedback, i published a new version `0.6.0`, it should resolve that issue, use

`Compressed`: Generates only .min.css file
`Expanded`: Generates only .css
`Expanded | Compressed`: Generates both
